name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v3
    - uses: Egabi-Solutions-Dev/ProjectManagement/blob/ed80c01f728c6423013f710161e956607e0b0004/.github/workflows/maven.yml@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
